Repository parkingbezplatny/app, pull requests merged in 2023-11, with the labels that each got.

#92 #91 #79 create pagination function for admin functionality and checks for user exist
  lib/nextauth/authOptions.ts
  lib/services/parking.ts
  lib/services/user.ts
Labels: backend

#94 Adjust parking spot db model to implement geojson #76
  components/map-tooltip.tsx
  components/map.tsx
  lib/nextauth/authOptions.ts
  lib/prisma/migrations/20231110193400_update_parking_schema/migration.sql
  lib/prisma/migrations/20231110195948_update_parking_schema_2/migration.sql
  lib/prisma/migrations/20231110200421_parking_model_update_3/migration.sql
  lib/prisma/migrations/20231110202352_parking_model_update_4/migration.sql
  lib/prisma/schema.prisma
  lib/services/parking.ts
  lib/services/user.ts
  lib/types/index.d.ts
  lib/validations/forms/createParking.validation.ts
  lib/validations/forms/updateParking.validation.ts
  lib/validations/forms/updateUserPassword.validation.ts
  lib/validations/forms/updateUserUsername.validation.ts
  next.config.js
  nextauth.d.ts
  parkings/okJsonParkingList.json
  parkings/parkingList.js
  parkings/parkingList.json
  parkings/parkingList.ts
  parkings/parkingListToDb.js
  parkings/parkingListToGeoJSON.js
Labels: backend, frontend, frontend view

#96 Bug with map component #95
  components/map-tooltip.tsx
  components/map.tsx
  lib/nextauth/authOptions.ts
  lib/prisma/migrations/20231115133247_parking_model_update_5/migration.sql
  lib/services/user.ts
Labels: bug, frontend

#102 Create profile page #99
  app/(pages)/(user)/profile/page.tsx
  components/password-modal.tsx
  components/username-modal.tsx
  lib/types/index.d.ts
Labels: frontend, frontend view

#104 Modify navbar to use menu instead of button #103
  app/(pages)/(user)/profile/page.tsx
  components/navbar.tsx
Labels: frontend, frontend view

#106 Removed unnecessary input in username change modal #105
  components/username-modal.tsx
Labels: frontend, frontend view

#107 Create admin page #98 #16
  .eslintrc.json
  app/(pages)/admin/layout.tsx
  app/(pages)/admin/page.tsx
  app/(pages)/admin/parking/page.tsx
  app/(pages)/admin/user/page.tsx
  components/admin-sidepanel.tsx
  components/navbar.tsx
  components/parking/create-parking-form.tsx
  components/parking/create-parking-modal.tsx
  components/parking/delete-parking-modal.tsx
  components/parking/update-parking-form.tsx
  components/parking/update-parking-modal.tsx
  components/tables/data-table.tsx
  components/tables/parking-columns.tsx
  lib/services/parking.ts
  lib/validations/forms/createParking.validation.ts
  lib/validations/forms/updateParking.validation.ts
  package-lock.json
  package.json
Labels: frontend, frontend view
