Repository parkingbezplatny/app, pull requests merged in 2024-01, with the labels that each got.

#118 Bugfixes and UI ux changes #117
  app/(pages)/admin/layout.tsx
  app/(pages)/admin/page.tsx
  app/(pages)/admin/parking/page.tsx
  app/(pages)/admin/user/page.tsx
  components/admin-sidepanel.tsx
  components/sidepanel.tsx
  components/tables/data-table.tsx
  components/tables/parking-columns.tsx
  components/user/change-password-modal.tsx
  lib/hooks/parkingHooks.ts
Labels: bug, frontend, frontend view

#123 #122 favorite fetch and everything with that
  app/(pages)/(user)/profile/page.tsx
  app/api/favorite/route.ts
  components/sidepanel.tsx
  lib/hooks/useFavorite.ts
  lib/hooks/useFavoriteMutation.ts
  lib/services/favorite.ts
Labels: backend, frontend, api, frontend view

#125 #124 fix password change
  app/(pages)/(user)/profile/page.tsx
  app/api/users/by-email/password-reset/route.ts
  app/api/users/password-reset/by-email/route.ts
  components/user/change-password-modal.tsx
  lib/providers/Providers.tsx
Labels: backend, frontend, api, frontend view

#132 #131 map as context to prevent again loading
  app/(pages)/(user)/dashboard/page.tsx
  app/(pages)/(user)/profile/page.tsx
  app/api/favorite/[parkingId]/route.ts
  components/map.tsx
  components/search.tsx
  components/sidepanel.tsx
  lib/context/mapContext.tsx
  lib/hooks/useFavorite.ts
  lib/hooks/useMapContext.tsx
  lib/providers/Providers.tsx
  lib/services/favorite.ts
  lib/services/parking.ts
Labels: backend, frontend, frontend view

#137 Display admin button in navbar based on users permissions #136
  app/(pages)/(user)/dashboard/page.tsx
  app/globals.css
  components/map-tooltip.tsx
  components/navbar.tsx
  components/search.tsx
  components/sidepanel.tsx
  components/tables/data-table.tsx
Labels: frontend, frontend view

#141 Adjusted map padding on sm devices #140
  app/globals.css
Labels: frontend, frontend view
